Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest:80, host:100, auto_correct: false  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  sudo apt-get install -y \
      ca-certificates \
      curl \
      gnupg \
      ufw \
      lsb-release
      
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo ufw --force enable
  sudo ufw allow 80/tcp
  sudo ufw allow 22
  sudo ufw allow 2222
  sudo apt-get update
  sudo apt-get install docker-ce docker-ce-cli containerd.io -y
  docker volume create nginx_data
  docker run --name some-nginx -d -p 80:80 nginx
    
  SHELL
  end